object Calculadora: TCalculadora
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu, biMinimize]
  BorderStyle = bsNone
  Caption = 'Calculadora'
  ClientHeight = 491
  ClientWidth = 393
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poDesktopCenter
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object header: TShape
    Left = 0
    Top = 0
    Width = 393
    Height = 35
    Align = alTop
    Brush.Color = cl3DLight
    Pen.Style = psClear
    OnMouseDown = headerMouseDown
  end
  object Close: TLabel
    Left = 360
    Top = 4
    Width = 26
    Height = 25
    Caption = ' X '
    Color = clRed
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -21
    Font.Name = 'Century Gothic'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Transparent = False
    OnClick = CloseClick
    OnMouseEnter = CloseMouseEnter
    OnMouseLeave = CloseMouseLeave
  end
  object Minimize: TLabel
    Left = 321
    Top = 4
    Width = 33
    Height = 25
    Caption = ' '#8212' '
    Color = clActiveCaption
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -21
    Font.Name = 'Century Gothic'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    Transparent = False
    OnClick = MinimizeClick
    OnMouseEnter = MinimizeMouseEnter
    OnMouseLeave = MinimizeMouseLeave
  end
  object Titulo: TLabel
    Left = 8
    Top = 5
    Width = 115
    Height = 25
    Caption = 'Calculadora'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -19
    Font.Name = 'Elephant'
    Font.Style = []
    ParentFont = False
    OnMouseDown = headerMouseDown
  end
  object GBGeral: TGroupBox
    Left = 0
    Top = 35
    Width = 393
    Height = 456
    Align = alClient
    TabOrder = 0
    object MemoTerminal: TMemo
      Left = 8
      Top = 6
      Width = 378
      Height = 105
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -37
      Font.Name = 'Time'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 0
      OnKeyPress = MemoTerminalKeyPress
    end
    object Porcentagem: TPanel
      Left = 8
      Top = 117
      Width = 90
      Height = 50
      BevelKind = bkSoft
      Caption = '%'
      Color = cl3DLight
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 1
      OnClick = PorcentagemClick
    end
    object BackSpace: TPanel
      Left = 296
      Top = 117
      Width = 90
      Height = 50
      BevelKind = bkSoft
      Caption = '<--'
      Color = cl3DLight
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 2
      OnClick = BackSpaceClick
    end
    object Clear: TPanel
      Left = 200
      Top = 117
      Width = 90
      Height = 50
      BevelKind = bkSoft
      Caption = 'C'
      Color = cl3DLight
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 3
      OnClick = ClearClick
    end
    object ClearUltimoNumero: TPanel
      Left = 104
      Top = 117
      Width = 90
      Height = 50
      BevelKind = bkSoft
      Caption = 'CE'
      Color = cl3DLight
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 4
      OnClick = ClearUltimoNumeroClick
    end
    object Fracao: TPanel
      Left = 8
      Top = 173
      Width = 90
      Height = 50
      BevelKind = bkSoft
      Caption = '1/x'
      Color = cl3DLight
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 5
      OnClick = FracaoClick
    end
    object Divisao: TPanel
      Left = 296
      Top = 173
      Width = 90
      Height = 50
      BevelKind = bkSoft
      Caption = ' '#247' '
      Color = cl3DLight
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentFont = False
      TabOrder = 6
    end
    object RaizQuadrada: TPanel
      Left = 200
      Top = 173
      Width = 90
      Height = 50
      BevelKind = bkSoft
      Caption = 'SQRT'
      Color = cl3DLight
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 7
      OnClick = RaizQuadradaClick
    end
    object ElevaADois: TPanel
      Left = 104
      Top = 173
      Width = 90
      Height = 50
      BevelKind = bkSoft
      Caption = 'X'#178
      Color = cl3DLight
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 8
      OnClick = ElevaADoisClick
    end
    object Sete: TPanel
      Left = 8
      Top = 229
      Width = 90
      Height = 50
      BevelInner = bvRaised
      BevelKind = bkSoft
      BevelOuter = bvNone
      Caption = '7'
      Color = clInactiveCaption
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 9
    end
    object Multiplicacao: TPanel
      Left = 296
      Top = 229
      Width = 90
      Height = 50
      BevelKind = bkSoft
      Caption = ' X '
      Color = cl3DLight
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentFont = False
      TabOrder = 10
    end
    object Nove: TPanel
      Left = 200
      Top = 229
      Width = 90
      Height = 50
      BevelInner = bvRaised
      BevelKind = bkSoft
      BevelOuter = bvNone
      Caption = '9'
      Color = clInactiveCaption
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 11
    end
    object Oito: TPanel
      Left = 104
      Top = 229
      Width = 90
      Height = 50
      BevelInner = bvRaised
      BevelKind = bkSoft
      BevelOuter = bvNone
      Caption = '8'
      Color = clInactiveCaption
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 12
    end
    object Quatro: TPanel
      Left = 8
      Top = 285
      Width = 90
      Height = 50
      BevelInner = bvRaised
      BevelKind = bkSoft
      BevelOuter = bvNone
      Caption = '4'
      Color = clInactiveCaption
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 13
    end
    object Subtracao: TPanel
      Left = 296
      Top = 285
      Width = 90
      Height = 50
      BevelKind = bkSoft
      BevelOuter = bvSpace
      Caption = ' - '
      Color = cl3DLight
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentFont = False
      TabOrder = 14
    end
    object Seis: TPanel
      Left = 200
      Top = 285
      Width = 90
      Height = 50
      BevelInner = bvRaised
      BevelKind = bkSoft
      BevelOuter = bvNone
      Caption = '6'
      Color = clInactiveCaption
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 15
    end
    object Cinco: TPanel
      Left = 104
      Top = 285
      Width = 90
      Height = 50
      BevelInner = bvRaised
      BevelKind = bkSoft
      BevelOuter = bvNone
      Caption = '5'
      Color = clInactiveCaption
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 16
    end
    object Um: TPanel
      Left = 8
      Top = 341
      Width = 90
      Height = 50
      BevelInner = bvRaised
      BevelKind = bkSoft
      BevelOuter = bvNone
      Caption = '1'
      Color = clInactiveCaption
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 17
    end
    object Adicao: TPanel
      Left = 296
      Top = 341
      Width = 90
      Height = 50
      BevelKind = bkSoft
      Caption = ' + '
      Color = cl3DLight
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentFont = False
      TabOrder = 18
    end
    object Tres: TPanel
      Left = 200
      Top = 341
      Width = 90
      Height = 50
      BevelInner = bvRaised
      BevelKind = bkSoft
      BevelOuter = bvNone
      Caption = '3'
      Color = clInactiveCaption
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 19
    end
    object Dois: TPanel
      Left = 104
      Top = 341
      Width = 90
      Height = 50
      BevelInner = bvRaised
      BevelKind = bkSoft
      BevelOuter = bvNone
      Caption = '2'
      Color = clInactiveCaption
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 20
    end
    object InverterSinal: TPanel
      Left = 8
      Top = 397
      Width = 90
      Height = 50
      BevelKind = bkSoft
      Caption = '+/-'
      Color = cl3DLight
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 21
    end
    object Resultado: TPanel
      Left = 296
      Top = 397
      Width = 90
      Height = 50
      BevelInner = bvRaised
      BevelKind = bkSoft
      BevelOuter = bvNone
      Caption = '='
      Color = clSkyBlue
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentFont = False
      TabOrder = 22
      OnClick = ResultadoClick
    end
    object Virgula: TPanel
      Left = 200
      Top = 397
      Width = 90
      Height = 50
      BevelKind = bkSoft
      Caption = ','
      Color = cl3DLight
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 23
    end
    object Zero: TPanel
      Left = 104
      Top = 397
      Width = 90
      Height = 50
      BevelInner = bvRaised
      BevelKind = bkSoft
      BevelOuter = bvNone
      Caption = '0'
      Color = clInactiveCaption
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 24
    end
  end
end
